/* Minified version, see original at main.development.js */
var oHash=window.location.hash;function itemLoader(){hash=window.location.hash;if((oHash!==hash)&&((oHash.indexOf('#!/set=')!==-1&&hash.indexOf('#!/set=')!==-1)||(oHash.indexOf('#!/photo_id')!==-1&&hash.indexOf('#!/photo_id')!==-1))){target='#gallery';loadingBox=false;}else{target='#content';loadingBox=true;}
if(hash.indexOf('#!/')>=0){link=hash.split('#!/');}else{link=hash.split('#!');}
data=link[2];link=link[1].replace(/\#\!/g,'?');hash='!/'+link;targetLink='?'+link;if(link.indexOf('home')==0){sidelink='.home';}else if(link.indexOf('about')==0){sidelink='.about';}else if(link.indexOf('recent')==0){sidelink='.recent';}else{sidelink='';}
$('#primarynav .active').removeClass('active');$('#primarynav '+sidelink).addClass('active');$this=$(target);if(target=='#gallery'){$this.find('.packery').css({'height':'0px','opacity':'0'});}else{$this.css('opacity','0');}
var loadingBox=$('<div id="loading-box" />');loadingBox.hide();$(target).before(loadingBox);loadingBox.fadeIn('slow');if(target=='#gallery'){$('#content-description').css('opacity','0');$('#content-description').before('<h3 id="loading-text">Loading...</h3>');$('#content-description').load(targetLink+' '+'#content-description'+' > *',function(){$('#loading-text').remove();$('#content-description').css('opacity','1');});}
$this.load(targetLink+' '+target+' > *',function(){if(target=='#gallery'){$this.find('.packery').css({'height':'auto','opacity':'1'});}else{$this.css('opacity','1');}
imagesLoaded($this,function(){$('.packery').packery({itemSelector:'.item',gutter:0});resizeVideo(function(){$('.packery').packery('layout');});parentNavScroller();if($('h3.title')[0]){document.title=$('h1 a').html()+" \273 "+$('h3.title').html();}else if(link){title=$('h1 a').html()+" \273 "+link.charAt(0).toUpperCase()+link.slice(1);if(title.indexOf('&')>0){title=title.split('&');title=title[0];}
document.title=title;}else{document.title=$('h1 a').html();}
loadingBox.fadeOut('slow',function(){$(this).remove();});});oHash='#'+hash;});};function parentNavScroller(){$('.parentnav .after').on('click',function(){$target=$(this).parent().find('ul');scroll=$target.scrollLeft()+160;$target.animate({scrollLeft:scroll},300);});$('.parentnav .before').on('click',function(){$target=$(this).parent().find('ul');scroll=$target.scrollLeft()-160;$target.animate({scrollLeft:scroll},300);});}
function resizeVideo(callback){var $allVideos=$("embed[src^='http://www.flickr.com'], object[data^='http://www.flickr.com']"),$fluidEl=$("li.video");$allVideos.each(function(){$(this).data('aspectRatio',this.height/this.width).removeAttr('height').removeAttr('width');});$(window).resize(function(){var newWidth=$fluidEl.width();$allVideos.each(function(){var $el=$(this);$el.width(newWidth).height(newWidth*$el.data('aspectRatio'));});}).resize();if(callback&&typeof(callback)==="function"){callback();}}
(function(hash){if(hash){itemLoader();}})(window.location.hash);$(window).load(function(){$(window).on('hashchange',function(){itemLoader();});$("#search").submit(function(e){console.log(e);search=encodeURIComponent($(this).find('input[type = search]').val());window.location.hash='!/search='+search;return false;});$('body').removeClass('firsttime');$('.packery').packery({itemSelector:'.item',gutter:0})
var pckry=$('.packery').packery('on','layoutComplete',resizeVideo())});